server:
  port: 18082

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

#spring.datasource.url=jdbc:mysql://localhost/test
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:org/tis/bootstudy/dao/mapping/*Mapper.xml
  typeAliasesPackage: org.tis.bootstudy.entity #实体扫描，多个package用逗号或者分号分隔
#  typeEnumsPackage: org.tis.bootstudy.entity.enums
  global-config:
    id-type: 5  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    field-strategy: 2 #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    db-column-underline: true #表名和字段名是否使用下划线命名，用于转换
    refresh-mapper: true #刷新mapper 调试神器
    #逻辑删除配置
    logic-delete-value: D
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazyLoadingEnabled: false
    multipleResultSetsEnabled: true